#!/bin/sh

EXECROOT=$HOME/git/tlgread-go

GRAN=$EXECROOT/dependencies/greek-analyses.txt
GRANIDT=$EXECROOT/dependencies/greek-analyses.idt
LSJ=$EXECROOT/dependencies/grc.lsj.xml
LSJIDT=$EXECROOT/dependencies/lsj.idt

$EXECROOT/bin/search -a $GRAN -idt $GRANIDT -dic $LSJ -dicidt $LSJIDT -w $*
